[package]
name = "astroplant-rs-api"
version = "0.1.0"
authors = ["Thomas Churchman <thomas@kepow.org>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.6.2"
chrono = "0.4"
warp = "0.1"
rumqtt = "0.30.1"
diesel = { version = "1.4.2", features = ["postgres", "numeric", "r2d2"] }
bigdecimal = "0.0.14"
ratelimit_meter = "4.1.1"
serde = { version = "1.0.97", features = ["derive"] }
erased-serde = "0.3"
serde_json = "1.0.40"
futures = "0.1.28"
tokio-threadpool = "0.1.15"