[package]
name = "astroplant-rs-api"
version = "0.1.0"
authors = ["Thomas Churchman <thomas@kepow.org>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.6.2"
astroplant-auth = { path = "./astroplant-auth" }
random-string = { path = "./random-string" }
once_cell = "0.2.6"
chrono = { version = "0.4", features = ["serde"] }
warp = "0.1.20"
bytes = "0.4.8"
rumqtt = "0.30.1"
diesel = { version = "1.4.2", features = ["postgres", "numeric", "r2d2", "chrono"] }
bigdecimal = "0.0.14"
ratelimit_meter = "4.1.1"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
erased-serde = "0.3"
validator = "0.9.0"
validator_derive = "0.9.0"
heck = "0.3.1"
futures = "0.1.28"
tokio-threadpool = "0.1.15"