[workspace]

members = [
  "astroplant-api",
  "astroplant-mqtt-ingest",

  # Libraries
  "astroplant-auth",
  "astroplant-mqtt",
  "astroplant-object",
  "astroplant-websocket",
  "random-string",
]
default-members = ["astroplant-api"]
