[package]
name = "rs-api"
version = "0.1.0"
authors = ["Thomas Churchman <thomas@kepow.org>"]
edition = "2018"

[dependencies]
warp = "0.1"
ratelimit_meter = "4.1.1"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"