[package]
name = "rs-api"
version = "0.1.0"
authors = ["Thomas Churchman <thomas@kepow.org>"]
edition = "2018"

[dependencies]
warp = "0.1"
diesel = { version = "1.4.2", features = ["postgres", "r2d2"] }
ratelimit_meter = "4.1.1"
serde = { version = "1.0.97", features = ["derive"] }
erased-serde = "0.3"
serde_json = "1.0.40"
futures = "0.1.28"
tokio-threadpool = "0.1.15"