name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install capnproto
      run: sudo apt-get install capnproto -y
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: astroplant
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: nix build
    - name: Check
      run: nix flake check
