name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install capnproto
      run: sudo apt-get install capnproto -y
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --release --verbose
    - name: Run tests
      run: cargo test --all --release --verbose
